--Crear Tabla de Clientes
CREATE TABLE [dbo].[CLIENTS](
	[ID_CLIENT] [int] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_TYPE] [varchar](50) NULL,
	[DOCUMENT_NUMBER] [varchar](50) NULL,
 CONSTRAINT [PK_CLIENTS] PRIMARY KEY CLUSTERED 
(
	[ID_CLIENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
--Finaliza tabla de clientes
--Se crea la tabla proveedores
CREATE TABLE [dbo].[SUPPLIER](
	[ID_SUPPLIER] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [text] NULL,
	[PHONE] [varchar](50) NULL,
	[ADDRESS] [varchar](50) NULL,
 CONSTRAINT [PK_SUPPLIER] PRIMARY KEY CLUSTERED 
(
	[ID_SUPPLIER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
--Finaliza la tabla Proveedores
--Se crea la tabla productos
CREATE TABLE [dbo].[products](
	[ID_PRODUCT] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NULL,
	[PRECIO] [varchar](50) NULL,
	[ID_PROVEEDOR] [int] NULL,
 CONSTRAINT [PK_products] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

--Se coloca la relacion entre la variable ID_SUPPLIER con la variable ID_CLIENT en la tabla [dbo].[SUPPLIER]
ALTER TABLE [dbo].[products]  WITH CHECK ADD  CONSTRAINT [FK_products_SUPPLIER] FOREIGN KEY([ID_PROVEEDOR])
REFERENCES [dbo].[SUPPLIER] ([ID_SUPPLIER])
GO

ALTER TABLE [dbo].[products] CHECK CONSTRAINT [FK_products_SUPPLIER]
GO
--Se finaliza la tabla productos
--Crear tablas de ventas
CREATE TABLE [dbo].[SALES](
	[ID_SALE] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENT] [int] NULL,
	[AMOUNT] [int] NULL,
	[ID_PRODUCT] [int] NULL,
 CONSTRAINT [PK_SALES] PRIMARY KEY CLUSTERED 
(
	[ID_SALE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
--Finaliza Tabla de ventas
--Se colocan las depedencias o relacion entre tablas
--Se coloca la relacion entre la variable ID_CLIENT con la variable ID_CLIENT en la tabla [dbo].[CLIENTS]
ALTER TABLE [dbo].[SALES]  WITH CHECK ADD  CONSTRAINT [FK_SALES_CLIENTS] FOREIGN KEY([ID_CLIENT])
REFERENCES [dbo].[CLIENTS] ([ID_CLIENT])
GO

ALTER TABLE [dbo].[SALES] CHECK CONSTRAINT [FK_SALES_CLIENTS]
GO
--Se coloca la relacion entre la variable ID_PRODUCT con la variable ID_CLIENT en la tabla [dbo].[products]
ALTER TABLE [dbo].[SALES]  WITH CHECK ADD  CONSTRAINT [FK_SALES_products] FOREIGN KEY([ID_PRODUCT])
REFERENCES [dbo].[products] ([ID_PRODUCT])
GO

ALTER TABLE [dbo].[SALES] CHECK CONSTRAINT [FK_SALES_products]
GO
--Finaliza relaciones

INSERT INTO CLIENTS(DOCUMENT_TYPE,DOCUMENT_NUMBER) 
VALUES 
('Cedula de Ciudadania', 1544789654),
('Cedula de Ciudadania', 1799846254),
('Cedula de Ciudadania', 14587454),
('Cedula de Ciudadania', 96852159),
('Cedula de Ciudadania', 45788965846)

INSERT INTO SUPPLIER(NAME,PHONE,ADDRESS)
VALUES
('Detodito',3216548794,'Calle 80 # 54-52'),
('Coca-Cola',3205487964,'Calle 26 # 28-26'),
('Cheetos',3005216987,'Calle 40 Sur # 54-55'),
('Pepsi',3125847965, 'Carrera 10 Sur # 27-25'),
('TodoRico',3154782698,'Calle 120 # 10-12'),
('Manzana',3256987412, 'Calle 100 # 54-62')

INSERT INTO products(DESCRIPTION,ID_PROVEEDOR,PRECIO)
VALUES
('DeTodito',1,2200),
('Coca-Cola',2,2500),
('Cheetos',3,1200),
('Pepsi',4,2500),
('TodoRico',5,2200),
('Manzana',6,1000)

INSERT INTO SALES(ID_CLIENT,ID_PRODUCT,AMOUNT)
VALUES
(1,1,10),
(1,2,10),
(2,6,10),
(3,6,5),
(4,3,1),
(5,4,2),
(2,5,1)

SELECT * FROM SALES

DELETE FROM SALES
WHERE ID_CLIENT=4

DELETE FROM SALES
WHERE ID_PRODUCT=2

SELECT * FROM SALES

UPDATE SALES
SET ID_CLIENT=1
WHERE ID_CLIENT=2

UPDATE SALES
SET ID_PRODUCT=3
WHERE ID_PRODUCT=6

SELECT * FROM SALES

SELECT * FROM products

UPDATE products
SET DESCRIPTION='DeTodito',ID_PROVEEDOR=1
WHERE CONVERT(VARCHAR(MAX),DESCRIPTION)='TodoRico'

UPDATE products
SET DESCRIPTION='Coca-Cola',ID_PROVEEDOR=2
WHERE CONVERT(VARCHAR(MAX),DESCRIPTION)='Pepsi'

UPDATE products
SET DESCRIPTION='Cheetos',ID_PROVEEDOR=3
WHERE CONVERT(VARCHAR(MAX),DESCRIPTION)='Manzana'

SELECT * FROM products