
SELECT C.ID_CLIENT,S.AMOUNT, p.DESCRIPTION
FROM CLIENTS C JOIN SALES S ON C.ID_CLIENT= S.ID_CLIENT JOIN products P ON S.ID_PRODUCT=P.ID_PRODUCT
WHERE C.DOCUMENT_NUMBER='1544789654' AND CONVERT(varchar(MAX), C.DOCUMENT_TYPE)='Cedula de Ciudadania'

SELECT S.NAME,S.PHONE,S.ADDRESS 
FROM SUPPLIER S JOIN products P ON S.ID_SUPPLIER=P.ID_PROVEEDOR
WHERE CONVERT(varchar(MAX), P.DESCRIPTION)='Cheetos'

SELECT P.DESCRIPTION,S.AMOUNT FROM products P JOIN SALES S ON P.ID_PRODUCT=S.ID_PRODUCT
ORDER BY S.AMOUNT DESC